### Récupération de tous les médias
GET http://localhost:8080/api/media/all

<> 2023-11-10T114822.200.json

### Récupération d'une page de médias avec le tri "par défaut" de l'API

### Récupération d'une page de médias triés par date
GET http://localhost:8080/api/media/all/date/0

<> 2023-11-10T114906.200.json

### Récupération d'une page de médias filtrés par genre
GET http://localhost:8080/api/media/all/genre/Action/0

<> 2023-11-10T115048.200.json

### Récupération d'une page de films OU séries
GET http://localhost:8080/api/media/all/type/MOVIE/0

<> 2023-11-10T115157.200.json

### Récupération des détails d'un média par son ID
GET http://localhost:8080/api/media/91484412-17b8-4594-9a29-3ecdf008e628

<> 2023-11-10T115248.200.json
