### Enregistrement d'un nouvel utilisateur et connexion
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "pseudo": "Endpoint test",
  "mail": "storm@mail.fr",
  "password": "aze123",
  "birthDate": "1994-03-26"
}

### Connexion de l'utilisateur (génération du token)
POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json

{
  "mail": "storm@mail.fr",
  "password": "aze123"
}

### Récupération des information de l'utilisateur
GET http://localhost:8080/api/user/407bbb4d-cb8d-4f74-b2cf-1f0160b67f28
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9ybUBtYWlsLmZyIiwiZXhwIjoxNzAwMTI3NzAyLCJpYXQiOjE3MDAwNDEzMDJ9.eMFRQdWtvv_-EZIRlEOr13duWcGPX2wDYKfHJFJDTJ8


### Modifications des données utilisateur
PATCH http://localhost:8080/api/user/407bbb4d-cb8d-4f74-b2cf-1f0160b67f28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9ybUBtYWlsLmZyIiwiZXhwIjoxNzAwMTI3NzAyLCJpYXQiOjE3MDAwNDEzMDJ9.eMFRQdWtvv_-EZIRlEOr13duWcGPX2wDYKfHJFJDTJ8

{
  "pseudo": "Test modifié",
  "birthDate": "1994-12-31"
}

### Modification du mot de passe de l'utilisateur
PATCH http://localhost:8080/api/user/407bbb4d-cb8d-4f74-b2cf-1f0160b67f28/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1haWwuZnIiLCJleHAiOjE2OTk3MTA1ODIsImlhdCI6MTY5OTYyNDE4Mn0.CCzgfjjWsRMgX_gpbZSLewA_TJIuZO7x6DnWSObTxXY

{
  "id": "407bbb4d-cb8d-4f74-b2cf-1f0160b67f28",
  "password": "qsd456"
}


### Modification des genres favoris de l'utilisateur
PATCH http://localhost:8080/api/user/genres/407bbb4d-cb8d-4f74-b2cf-1f0160b67f28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1haWwuZnIiLCJleHAiOjE2OTk3MTA1ODIsImlhdCI6MTY5OTYyNDE4Mn0.CCzgfjjWsRMgX_gpbZSLewA_TJIuZO7x6DnWSObTxXY

{
  "userId": "407bbb4d-cb8d-4f74-b2cf-1f0160b67f28",
  "genreIdList": [4, 8, 22]
}

### Récupération des recommandations de films/séries pour un utilisateur
GET http://localhost:8080/api/recommendations/407bbb4d-cb8d-4f74-b2cf-1f0160b67f28
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1haWwuZnIiLCJleHAiOjE2OTk3MTA1ODIsImlhdCI6MTY5OTYyNDE4Mn0.CCzgfjjWsRMgX_gpbZSLewA_TJIuZO7x6DnWSObTxXY
